FROM ubuntu:14.04
LABEL MAINTAINER=xuyf75@chinaunicom.cn

WORKDIR /root
RUN apt-get update && apt-get install -y openssh-server wget curl unzip telnet

ADD soft/jdk-8u172-linux-x64.tar.gz /opt/

ENV JAVA_HOME /opt/jdk1.8.0_172
ENV JRE_HOME $JAVA_HOME/jre
ENV CLASSPATH .:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
ENV PATH $JAVA_HOME/bin:$PATH

RUN ssh-keygen -t rsa -f ~/.ssh/id_rsa -P '' && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
